/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/status` | `/status`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/components/StatusCard` | `/components/StatusCard`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/status` | `/status`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/components/StatusCard` | `/components/StatusCard`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/status${`?${string}` | `#${string}` | ''}` | `/status${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/components/StatusCard${`?${string}` | `#${string}` | ''}` | `/components/StatusCard${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/status` | `/status`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/components/StatusCard` | `/components/StatusCard`; params?: Router.UnknownInputParams; };
    }
  }
}
